### ISSUE TITLE
S21과 S22에서 이미지배너가 가끔식 노출되지 않는 현상

### ISSUE THREAD

**Issue by hyungyoung123** [naver/nam-sdk-android#15]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/naver/nam-sdk-android/issues)

### Version

4.3.6

### AGP Version

7.4.2

### Android version

API 31, AOS 12, One UI 4.1

### Device

Samsung Galaxy S21+, S22

### Steps to Reproduce

웨더퐁앱으로 테스트하는 경우에 발생하며 주로 발생하는 Case는 다음과 같습니다.
앱 다운로드 경로 : https://drive.google.com/file/d/1AozSleXzlPRRTp2h9XQ_V3fPVMsiR2Pc/view?usp=drivesdk

1.앱설치 > 실행
2. 앱실행 > 종료 > 10분 후 > 재실행 

### Expected Result

이미지배너(높이 185)가 항상 노출되어야 함

### Actual Result

이미지 배너(높이 185)가 가끔식 미노출이 되며, 손으로 해당 영역을 터치하면 배너가 display됨.

광고는 수신된 상태인데 rendering이 안되는 현상으로 보임.

구형 단말기인 S9, S10에서는 발생하지 않으며, S21과 S22에서만 나타나는 현상임

현상에 대한 영상 : https://photos.app.goo.gl/zpXrVJ4okx2bw89a6

**Comment by kidoohan** [comment]
안녕하세요:)

높이 185 이미지 배너라 함은 아래 이미지상 빨간색 동그라미가 쳐진 위치의 배너 광고를 이야기 하시는걸까요?

<img width="400" src="https://user-images.githubusercontent.com/15433735/183555558-5d24cff9-ca97-4260-8ec4-e0877a2e5f5d.jpg">

**Comment by hyungyoung123** [comment]
네 맞습니다. 
참조 영상 : https://photos.app.goo.gl/zpXrVJ4okx2bw89a6

**Comment by kwonjae-lee** [comment]
Galaxy S21+ 기기인데 재현이 안되네요...
종료 시키면 웨더퐁 맨 상단으로 이동하는 것 같은데요
앱 종료 이후 10분 정도 대기하는게 맞을지요?

**Comment by kwonjae-lee** [comment]
@hyungyoung123 님
클릭하거나 백그라운드 이동 등 생명주기 변화가 생길 때 광고 영역이 사라진 후 광고가 재 호출되는 것 같은데요.
광고 재 호출 시점이 어떻게 되는지 알 수 있을까요?

**Comment by hyungyoung123** [comment]
@kwonjae-lee 님,
광고 재호출 시점은 개발자에게 github에 답변을 등록해 주실 것을 요청했습니다.
상기 미노출 현상은 상시 나타나는 것은 아니고, 최초 설치 > 실행했을 때 가장 잘 나타나며, 종료 후 일정 시간 지난 후에 재 실행 했을 때  종종 나타나는 것 같습니다. 종료 후 바로 재실행하면 잘 안나타나기에 종료 후 10분 정도는 등록한 것입니다.

**Comment by kidoohan** [comment]
설치 초기 및 종료 후 특정 시간 이후에 웹뷰가 오동작하는 걸로 보아 혹시나 해서 여쭤보는데요. 

혹시, 앱내에서 웹뷰 api 중 pauseTimers 혹은 resumeTimers 를 호출하는 부분이 있을지 확인 부탁드립니다:)

**Comment by HarryJhin** [comment]
앱 개발자입니다.

@kwonjae-lee 

해당 액티비티에서는 `onResume()` 생명 주기에서 재호출되고 있습니다.

@kidoohan 

사용하지 않고 있습니다.

**Comment by kwonjae-lee** [comment]
@HarryJhin @hyungyoung123 님
에러 상황이 재연되지 않아 추가로 몇가지 여쭤봅니다.

1. 앱 종료 이후 재 실행하면 (혹은 앱 삭제 이후 설치, 실행)
    - 아래와 같이 첫 화면이 보여지는데요.
![Screenshot_20220809-134151_Weatherpong](https://user-images.githubusercontent.com/98582953/183566393-1a911d87-154d-4317-a1a2-c0ce4a71ef3a.jpg)
     - 스크롤 내렸을 때 문제가 발생하는 상황인지요?
![Screenshot_20220809-134200_Weatherpong](https://user-images.githubusercontent.com/98582953/183566543-f780fd04-b82a-439a-8012-80a799de602b.jpg)
2. 광고가 보이지 않을 때, 가만히 기다리면 보여지는 상황인지요?
광고 영역 터치나 BG 이동 등 아무 액션하지 않았을 때 어떻게 되는지요?
3. 발생 빈도가 어떻게 되는지 대략적으로 알 수 있을까요?

**Comment by HarryJhin** [comment]
@kwonjae-lee 님

1. 앱 종료 이후 재 실행하면

    스크롤해서 내려갔을 때 이미지가 보이지 않는 현상입니다. Layout Inspect로 확인하면 이미지가 랜더링된 것으로 보이나 실제 기기에서는 보이지 않습니다.

2. 광고가 보이지 않을 때, 가만히 기다리면 보여지는 상황인지요?

    계속 보이지 않습니다.

3. 발생 빈도가 어떻게 되는지 대략적으로 알 수 있을까요?

     특정 조건을 만족하는 환경에서 거의 100%의 확률로 관측됩니다.

**Comment by hyungyoung123** [comment]
@kwonjae-lee 
https://photos.app.goo.gl/RVPxgHcfxkh9Me6i8

1. 185배너는 스크롤을 내려야만 볼 수 있습니다. 그래서 스크롤을 내렸을 때입니다.
2. 기다려도 보이지는 않습니다. 손으로 터치를 하면 바로 나타납니다.
3. 발생 빈도가 단말기 영향을 좀 타는 것 같습니다. 즉 같은 기종이라도 나타나지 않는 경우도 있습니다. 
    - 발생빈도는 랜덤합니다만, 나타나는 단말기에서는 10분 주기로 테스트를 해 본다면 1hr에 1번 이상 나타나는 것으로 보입니다.
 
이 문제가 반드시 Naver SDK만의 issue인지도 명확하지는 않습니다. 다른 하위 기종에서는 전혀 나타나지 않는데 최신기종(S21/S22)에서만 목격되고 있습니다. 갤럭시 S10+(AOS 12)에서도 이런 현상이 없으며, 현재까지는 S21/S22에서만 목격되고 있습니다.

**Comment by hyungyoung123** [comment]
https://photos.app.goo.gl/N6cLoZ3EpKwemomj8

**Comment by kwonjae-lee** [comment]
@HarryJhin
저희가 보유한 테스트 기기에선 재연이 안되다보니 계속 여쭤보게 되네요
양해 부탁드립니다~

햄버거 버튼을 누르거나 클릭하면 바로 광고 영역이 보이지 않게 되는데요.
해당 부분 구현된 것 공유해 주실 수 있을까요?
그리고 `GfpBannerAdOptions` 에 어떤 값을 설정해서 사용 중이신지도 알려주시면 확인에 도움이 될 것 같습니다~

**Comment by kidoohan** [comment]
@HarryJhin  
더해서, 번거로우실 수 있겠지만 해당 케이스의 상황이 재현될 때 Layout Inspector 로 확인시 문제되는 광고 영역에서의 `GfpBannerAdView` 의 너비 및 높이값이 어떤 값인지 알려주시면 원인 파악에 도움이 될 것 같습니다:)

**Comment by HarryJhin** [comment]
@kwonjae-lee 님

`GfpBannerAdOptions`는 다음과 같이 사용하고 있습니다.

```kotlin
val adOptions = GfpBannerAdOptions.Builder()
    .setBannerViewLayoutType(BannerViewLayoutType.FLUID_WIDTH)
    .setHostParam(HostParam.Builder()
        .build())
    .build()
```

햄버거 버튼은 정확히 어떤 버튼을 말하시는 것인지 모르겠어서, 좀 더 상세하게 말씀해주시면 감사하겠습니다.

@kidoohan 님

문제되는 기기를 현재 테스트할 수 없어서 해당 속성 값은 답변 드리기 어렵습니다.

**Comment by kidoohan** [comment]
그렇다면, GfpBannerAdView가 포함되는 ll_adViewSecond 의 높이값은 wrap_content 으로 설정하셨나요? 아니면 185dp 로 고정해두셨을까요?

**Comment by HarryJhin** [comment]
@kidoohan 님

높이는 `wrap_content`으로 설정되어 있습니다.

```xml
<LinearLayout
    android:id="@+id/ll_adViewSecond"
    ...
    android:layout_height="wrap_content"
    ...
```

**Comment by kwonjae-lee** [comment]
@HarryJhin 님
'최근 앱 보기' 버튼을 햄버거 버튼으로 잘못 여쭤봤네요... 죄송합니다~
클릭하거나 백그라운드로 이동하는 경우 광고 영역이 사라지게 되어 있는 것 같아서요
해당 부분이 어떻게 되어 있는지 여쭤봤습니다~

**Comment by kidoohan** [comment]
답변 감사합니다:)

`wrap_content` 로 설정하신 상황에서 위 에러 상황을 유추해본다면, 

- `GfpBannerAdView` 의 onMeasure->onLayout 까지는 타면서 GfpBannerAdView 의 높이값은 제대로 계산됨.
- 이후 WebView 내에서 invalidated() 가 정상적으로 수행되지 않으면서 draw 가 안 됨 
- 이후 touch 이벤트와 같은 User interaction 이 포함될 경우에만 invalidated() 가 호출되었다 정도까지만 유추되네요...

현재까지 여러 상황을 가정하고 테스트 해보았을 때 재현이 안되고 있고 그 동안 네이버 내부 매체들에 GfpBannerAdView 가 적용되었을 때 위와 같은 케이스가 나온 적이 없어서 원인 파악에 지연이 발생되고 있습니다. 

좀 더 테스트를 해보고 공유드리도록 하겠습니다. 

한가지 더 질문 드리자면, 해당 광고 아래 영역들에 붙게되는  구글 배너광고 또한 GfpBannerAdView 와 동일하게 `onPause()` 에서 광고 영역을 removeView(동작상 그런 것으로 보여서요. 아니라면 확인 부탁드리겠습니다.) 또는 destroy() 하고 onResume() 에서 다시 광고 요청을 하는 형태로 동일하게 구현되어 있을까요?

**Comment by HarryJhin** [comment]
@kwonjae-lee @kidoohan 님

`onPuase()`에서 모든 광고를 삭제하고, `onResume()`에서 다시 광고를 load합니다.

저희가 테스트하면서 발견한 특이 사항 한 가지를 공유해드리겠습니다.

문제가 되었던 테스트 기기에서 개발자 옵션의 최소 너비 옵션을 기본 값에서 1이라도 올릴 경우 재현되지 않았습니다.

내리는 경우는 테스트해보지 않았습니다.

**Comment by kidoohan** [comment]
@HarryJhin 님 답변 감사합니다. 

이슈가 생기는 상황은 소재 상관없이 발생하는 걸로 봐도 괜찮을까요?
공유주신 영상에서 이슈가 됐었던 소재들(STL?, Bijou 마스크) 응답을 받지 못했는데 이외 자주 나오는 소재, 특히 The SKY 52 분양 관련 소재에서도 동일하게 재현되는지 궁금해서 여쭤봅니다:)

**Comment by kidoohan** [comment]
@HarryJhin 님, 죄송하지만, `GfpBannerAdOptions` 설정시 `BannerViewLayoutType` 을 `FIXED` 로 설정해도 문제되는 기기에서 이슈가 재현되는지 확인해주실 수 있을까요? 

저희가 재현이 안되다보니 질문도 많고 부탁도 많이 하게 되네요 ㅜ

**Comment by hyungyoung123** [comment]
@kidoohan 님, 소재와 위 Fixed 설정 Test에 대해서는 시간이 좀 소요되므로, 저녁에 Test를 해보고 내일 오전에 회신을 드리겠습니다.

**Comment by hyungyoung123** [comment]
@kidoohan 님,
The SKY 52 소재 자체가 나타난 적이 없어서 확인을 할 수 없었고, 금일 버거킹소재에서도 재현되었습니다.

![Screenshot_20220810-084436_Weatherpong](https://user-images.githubusercontent.com/89900394/183783692-59aa8be7-6d3e-4330-9ca2-7aa659f0c480.jpg)

**Comment by kidoohan** [comment]
@hyungyoung123 님 답변 감사합니다:)

FIXED 로 설정시에도 이슈가 재현되는 케이스가 있었던 걸까요? 위 사항이 저희가 이슈를 재현해보는데 큰 도움이 될 듯 하여 문의 드립니다:)

**Comment by hyungyoung123** [comment]
@kidoohan 
> FIXED 로 설정시에도 이슈가 재현되는 케이스가 있었던 걸까요? 위 사항이 저희가 이슈를 재현해보는데 큰 도움이 될 듯 하여 문의 드립니다:)
   A) S21/S22로 테스트를 하고 있고, 1hr 정도 테스트를 해 본 결과 S21에서 1번 발생하였습니다. 감소수준을 수치로 말씀드리기는 어려우나, 기존보다는 재현현상 감소가 느껴집니다. 금일 계속 테스트를 해보고 결과를 공유해 드리겠습니다.
