### ISSUE TITLE
AOS 시스템 다크모드 설정 관련 확인 요청

### ISSUE THREAD

**Issue by NAM-Ad** [naver/nam-sdk-android#16]
### Problem Statement

확인요청
-
**OK캐쉬백 AOS앱** 기준, 아래 내용 확인 부탁드립니다. 

/cc @HarryJhin @hyungyoung123

----

안드로이드 시스템 다크모드를 적용한 상태에서 Ad Mute 설정을 하게 되면,
- 네이티브 심플 (NS)은 다크모드가 적용되나, 
- Web-View 배너(Banner)는 다크모드 적용이 되지 않아 이질감이 있는 상황입니다. 

OK캐시백은 다크모드 미지원 앱에 해당하므로,
아래와 같이 `GfpNativeSimpleAdOptions `적용되도록 설정 부탁드립니다. 
> 기본값 system -> light 로 변경 필요

```

new GfpAdLoader.Builder(requireActivity(), adParam)
        .withNativeSimpleAd(
                new GfpNativeSimpleAdOptions.Builder()
                        .setAdChoicePlacement(
                                GfpNativeSimpleAdOptions.ADCHOICES_TOP_RIGHT)
                        .setTheme(GfpTheme.LIGHT)
                        .build(),


```

---- 

아래는 화면 예시입니다. 

### `(1) 네이티브 심플 (NS)`
> ![image](https://user-images.githubusercontent.com/109189952/184102353-f10bd794-3118-427f-ae1c-f42b3c44c7f3.png)

### `(2) Web-View 배너(Banner)`
> ![image](https://user-images.githubusercontent.com/109189952/184102296-2819d77a-8325-4be3-ba5e-177008de9854.png)

**Comment by NAM-Ad** [comment]
@hyungyoung123 님, 안녕하세요? 
네이버 오형석입니다.

상기 공유드린 안드로이드 다크모드 설정 관련,
OK캐쉬백 앱에 탑재된 **NAM SDK 업데이트가 필요**한 것으로 확인되었는데요. 

매체 측 대응 방안 문의드리고자 합니다.
> 1,2안 모두 NAM SDK 업데이트가 필요하며, 대응 희망 시기에 따라 선택하시면 됩니다.
> 급하게 대응할 필요없다고 판단되시면 app set id 대응 시기에 맞춰서 차주 NAM SDK 업데이트 하는 것이 어떨지요? (2안)

- **(1) ASAP 대응**
  - 대응시점 : 매체 선택
  - 대응사항 :  `GfpNativeSimpleAdOptions ` > `setTheme(GfpTheme.LIGHT)`로 변경 필요
- **(2) 차주 대응**
  - 대응시점 : 차주 목표 (TBD)
  - 대응사항 : 매체 대응 불필요
    - default 설정에 `GfpNativeSimpleAdOptions ` > `setTheme(GfpTheme.LIGHT)` 반영
  > 차주 전달드리는 버전에는 대체 식별자(app set id)에 대한 가이드가 추가될 예정입니다.
  > app set id 대응 차원에서 업데이트가 필요한 상황이므로, 한번에 업데이트 하는 것이 어떨지 의견드립니다.

**Comment by hyungyoung123** [comment]
@NAM-Ad 오형석님,
Ad Mute 설정 case 발생이 매우 낮을 것 같고, UX적으로도 이질감이 심하다고 보이지를 않아서 긴급 재배포할 수준은 아닌 것으로 보입니다. (UX적인 부분이기에 고객불만 접수도 없을 것 같음)
일관성 측면에서 app set id건을 반영할 때 적용하도록 하겠으며, 다른 앱에서도 동일 방식으로 반영을 하도록 하겠습니다.

**Comment by kwonjae-lee** [comment]
@hyungyoung123 님 안녕하세요~
4.4.0 버전 배포하면서 GfpTheme 기본 값을 SYSTEM -> LIGHT 로 변경 적용 하였습니다.
확인 한번 부탁드립니다 (__)

cc. @NAM-Ad
