### ISSUE TITLE
GfpNativeSimpleAdView 좌우 여백 영역 클릭 이슈

### ISSUE THREAD

**Issue by myung6024** [naver/nam-sdk-android#22]
### Problem Statement

폴드 처럼 가로가 긴 해상도에서 광고를 호출했을 경우 광고의 좌우 여백 영역은 터치가 되지 않습니다.

혹시 의도된 작동이거나 제가 잘못 설정한 것이 있을까요?

광고 터치 영역이 `match_parent`가 되는 것을 예상했었습니다.

<img width="633" alt="스크린샷 2022-12-12 오후 6 23 15" src="https://user-images.githubusercontent.com/11826473/207008968-4ac81798-72e2-43ac-9f24-c80cfd3376f5.png">

**Comment by kidoohan** [comment]
안녕하세요. 위 부분은 SDK 에서 의도된 부분으로써 이미지 영역을 클릭했을 때에만 클릭 이벤트가 발화됩니다:)

**Comment by myung6024** [comment]
ios에서는 사이즈를 지정할 수 있어서 여백도 클릭이 가능한데 aos는 따라 사이즈를 조절할 수 없어서 OS간 동작의 차이가 발생하는 이슈가 있습니다. @kidoohan

**Comment by kidoohan** [comment]
ios 개발에 문의 해보겠습니다. NativeSimpleAd 같은 경우, 일반적인 배너(WebView) 광고와 같은 유형으로써 좌우 여백은 클릭시 랜딩이 안되는 것이 맞는데요. 예를 들어서 좌우 너비가 긴 기기 또는 landscape 상태로 configuration 이 변경되었을 때에 좌우 여백이 크게 생기는 경우 해당 상품을 클릭시 랜딩 되는 것이 오동작으로 비춰질 수 있어서요.

**Comment by myung6024** [comment]
리마인드 드립니다 🙏  @kidoohan

**Comment by kidoohan** [comment]
답변이 늦어서 죄송합니다. 오늘 중으로 답변 드리도록 하겠습니다:)

**Comment by kidoohan** [comment]
@myung6024 님 android 스펙대로 변경하는 것으로 이야기가 되었습니다. ios 쪽의 클릭 부분은 차기 버전 또는 차차기 버전에 배포될 것으로 보입니다:)

**Comment by myung6024** [comment]
앗 그렇군요 확인 감사합니다!
의도된 동작으로 확인하고 이슈 닫도록 하겠습니다 🙇
