### ISSUE TITLE
Android SDK com.naver.gfpsdk:nam-core 참조 빌드시 발생하는 문제에 대해 문의드립니다

### ISSUE THREAD

**Issue by zaphike** [naver/nam-sdk-android#28]
### Problem Statement

SDK 버전 : com.naver.gfpsdk:nam-core:5.3.0

SDK Proguard 설정으로인해 발생가능한 문제가 있어보여 확인 부탁드립니다.

External Libraries 에서 해당 라이브러리 jar 파일을 확인해봤는데요.

패키지명이 기본적으로 설정되는 a, b… 로 시작해서요.

라이브러리를 포함할 때 이처럼 패키지명이 a.a 로 시작하는 다른 라이브러리가 있다면 해당 클래스를 찾지 못해서 빌드에 실패하는 문제가 있는것으로 알고 있습니다.

연관 이슈를 함께 첨부해두겠습니다

https://github.com/helpcrunch/android-sdk-demo/issues/33

**Comment by kwonjae-lee** [comment]
제보 감사합니다 (__) 확인 후 말씀드리겠습니다!

**Comment by kwonjae-lee** [comment]
@zaphike 님
해당 이슈에서 안내된 것 처럼 저희 쪽에서 지정하는 패키지 이름으로 수정이 필요할 것 같습니다.
다음 배포가 4월 중순에 예정되어 있는데요.
혹시 지금 불편을 겪고 계실까요?

**Comment by zaphike** [comment]
혹시 수정이 되었을까요?
늦은 답변이지만, 다른 라이브러리에 수정 요청해서 사용 중입니다.

**Comment by kwonjae-lee** [comment]
@zaphike 안녕하세요~
다음 버전에 말씀주신 부분 반영 될 예정인데요.
죄송하지만 내부 QA가 진행중이라 수정한 버전은 아직 배포되지 않았습니다.
5월 초중순으로 변경 되었습니다.

**Comment by zaphike** [comment]
@kwonjae-lee 님, 안녕하세요.
혹시, QA 완료되었는지, 배포 일정은 어떻게 되는지 확인 부탁 드립니다.
저희가 개발중인 신규 버전에 적용 가능 한 일정일지 검토하려고 합니다.
감사합니다.

**Comment by kwonjae-lee** [comment]
@zaphike 님 안녕하세요~
일정이 딜레이 되면서 아직 QA진행 중 입니다.
5월 말 배포 (늦어도 6월초)로 미루어졌습니다.
불편을 드려 죄송합니다~ (__)
sdk를 적용한 서비스 배포의 일정은 고정되어 있으므로 늦어도 6월 초엔 배포 될 예정입니다.

**Comment by kidoohan** [comment]
@zaphike 님 안녕하세요. NAM SDK 6.0.0 버전이 배포되어 공유드립니다. 공유주신 이슈는 해결되었고 이슈 없으시다면 해당 이슈 close 하겠습니다:)

**Comment by zaphike** [comment]
중복 될 수 있는 a.a.x.x package 명 정리된 것으로 확인하였습니다.
감사합니다~

**Comment by kidoohan** [comment]
그럼 이슈 종료된 것으로 확인하고 닫도록 하겠습니다:) 확인 감사합니다.
