### ISSUE TITLE
load callback

### ISSUE THREAD

**Issue by zaphike** [naver/nam-sdk-android#3]
광고 성공에 대한 callback 에 대해 문의 드립니다.
onNativeSimpleAdLoaded 를 사용하고 있으나, 아래와 같이 이후 onError callback 이 발생하고 있습니다.
1. GfpNativeSimpleAdView 에 대해 parent's removeView() 를 적용하여도 아래와 같은 오류 메시지가 발생하고 있습니다.
2. 광고 성공에 대한 최종 callback 은 어떻게 확인해야 하는지요. 

D/NaverNSView: onNativeSimpleAdLoaded ad info[{
      "requestId": "9692bbc0-eabd-11ec-b446-010600000000",
      "adCallLatency": 201,
      "totalLoadLatency": 318,
      "adapterLoadLatency": 116,
      "loadedAdapterName": "NdaNativeSimpleAdapter",
      "adapterResponses": [
        {
          "adapterName": "NdaNativeSimpleAdapter",
          "loadLatency": 116,
          "loadErrorLatency": 0,
          "error": "null"
        }
      ],
      "errors": []
    }]
E/NaverNSView: onError {
      "errorCode": 3310,
      "errorSubCode": "GFP_NO_FILL",
      "errorMessage": "The specified child already has a parent. You must call removeView() on the child's parent first.",
      "errorObject": "null",
      "stat": "2"
    }
D/MixedAdView: NAVER_NS onLoad ad_id = AOS_NATIVE_TEST, return code = NOT_DEFINED_ERROR

**Comment by kidoohan** [comment]
안녕하세요:) GFP SDK Dev 한기두입니다.

1번 문의에 대한 부분은 위 에러 상황을 보면 `removeView` 가 정상적으로 처리되지 않은 것으로 보이는데요.
혹시 어떤 형태로 `removeView` 를 수행하셨는지 코드를 공유해주시면 감사하겠습니다.

아마 `recyclerView` 안에서  사용하셨다면 광고 View 가 add 된 parent 안에서 확실하게 remove 를 시키기 위해서는 아래와 같은 코드로  `removeView` 를 호출하셔야 합니다.

```java
if (adView.getParent() != null) {
    ((ViewGroup) adView.getParent())
            .removeView(adView);
}
```

2번째 문의 사항에 대한 답변으로는 광고 성공이라면 네이티브 광고의 경우, 네이티브 광고 렌더링에 필요한 asset 들의 로드 성공과 렌더링 성공 단계로 최종적인 렌더링 성공까지의 확인을 하실 수 있는데요.

렌더링 성공 여부는 `AdEventListener#onAdImpression` 콜백을 통해 확인하실 수 있습니다.

**Comment by zaphike** [comment]
안녕하세요. SKP  박효재 입니다.
1번 답변에 대해 의견 드립니다.
=> parent 에서 loadAd 호출 전 : removeView(mNaverNSView);
    // support naver ns
    private void loadAdNaverNS(final MixedAd_v2.Unit unit) {
        final String id = unit.unitId;
        if (DEBUG) {
            Qlog.d(TAG, "NAVER loadAdNaverNS ad_id = " + id);
        }

        removeView(mNaverNSView);

        mNaverNSView.setAdId(unit.unitId);
        mNaverNSView.setEventListener(new AdsEventListener() {
            @Override
            public void onLoad(@androidx.annotation.Nullable String type, @androidx.annotation.Nullable String id, @androidx.annotation.Nullable String code) {
                if (DEBUG) {
                    Qlog.d(TAG, "NAVER_NS onLoad ad_id = " + id + ", return code = " + code);
                }

                if ("0".equals(code)) {
                    //        android:layout_width="match_parent"
                    //        android:layout_height="wrap_content"
                    addView(mNaverNSView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
                    updateVisibleView(AD_TYPE_NAVER_NS);
                    sendOnLoad(AD_TYPE_NAVER_NS, unit.unitId, code);
                } else {
                    next(code);
                }

            }

            @Override
            public void onClick(@androidx.annotation.Nullable String type, @androidx.annotation.Nullable String id, @androidx.annotation.Nullable String marketingId) {
                sendOnClick(AD_TYPE_NAVER_NS, id, null);
            }
        });

        mNaverNSView.loadAd(false);
    }

**Comment by zaphike** [comment]
한기두 님,
1. 공유 드린 에러 메시지는 라이브러리 내에서 addView 중 발생하는 현상인것으로 보이는 메시지인 것으로 보이는데, native 에서 removeView 를 해야 한다는게 잘 이해가 가지 않는 것 같습니다.
2. removeView 상태로 impress 호출되지 않습니다.

**Comment by kidoohan** [comment]
> 한기두 님,
> 
> 1. 공유 드린 에러 메시지는 라이브러리 내에서 addView 중 발생하는 현상인것으로 보이는 메시지인 것으로 보이는데, native 에서 removeView 를 해야 한다는게 잘 이해가 가지 않는 것 같습니다.
> 2. removeView 상태로 impress 호출되지 않습니다.

1. 에러 메시지를 보고 유추해보면, `GfpNativeSimpleAdView` 가 특정 `ViewGroup` 에 add 된 상태에서 또다시 다른 또는 같은 `ViewGroup` 에 addView 해서 발생하는 오류로 보입니다. 이 케이스에 대해서 이야기 드린 부분입니다.
2. `GfpNativeSimpleAdView` 가 정상적으로 렌더링 되어야지만 impression 이벤트가 발생합니다.

**Comment by zaphike** [comment]
> 

1.  첨부 드린 로그는 onError callback 에서 발생한 로그로, (기존에는) native 에서 addView 하지 않습니다.
2. 말씀 하신 대로라면, adViw 는 addView 되어 있어야 렌더링 되는 것으로 보이는데, 현재 addView 상태에서 onError 가 발생하고 있습니다.

**Comment by kidoohan** [comment]
> > 
> 
> 1. 첨부 드린 로그는 onError callback 에서 발생한 로그로, (기존에는) native 에서 addView 하지 않습니다.
> 2. 말씀 하신 대로라면, adViw 는 addView 되어 있어야 렌더링 되는 것으로 보이는데, 현재 addView 상태에서 onError 가 발생하고 있습니다.

1 번 항목은 저희쪽에서도 체크가 필요할 듯 합니다. 외부 배포용 빌드에서 오류가 발생했을 수도 있어서요. 
다만, 좀 더 정확한 원인 파악을 위해서 더 많은 정보들이 필요할 듯 한데요. 혹시 저희쪽 광고 사용시 별도로 wrapping 해서 사용하는 부분이 있거나 문제가 되지 않는 범위내에서 코드 공유 가능하실까요?  

위 이슈는 대부분 앞서 공유드렸던 내용과 같이 이미 parent 를 가지고 있는 view 를 다시 addView 하는 케이스에서만 발생하는 오류였던 터라 저희쪽에서는 그 동안 별도로 발생하지 않았던 이슈였어서 문의 드립니다. 

그리고 2번 항목은 addView 된 상태로 50% 노출이 1초간 정상적으로 보장되어야지 impression 이벤트가 발생하는거라서 에러가 발생할 경우, impression 이벤트가 발생하지 않는 것이 정상동작으로 보입니다.

**Comment by zaphike** [comment]
https://github.com/naver/nam-sdk-android/blob/main/doc/native_simple.md#4-1-%EA%B4%91%EA%B3%A0-%EB%A1%9C%EB%93%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EC%88%98%EC%8B%A0---gfpnativesimpleadonnativesimpleadloadedlistener
문서 상으론 onNativeSimpleAdLoaded 에서 로드 이벤트를 확인 하는 것이 맞는 것 같아 보이는데요.
실제로, load 처리를 하지 않는 경우 impress 이벤트가 수신되지 않고 있습니다.

사용한 코드는 가이드에 있는대로 적용하였기 때문에 도움이 되지 않을것 같습니다.
다만, 해당 화면에 visible 상태를 load 성공시에 switching 하도록 적용되어 있어, load 이벤트를 처리 하지 않으면 impress 이벤트 발생하지 않을 수는 있을것 같습니다.

추가로, onNativeSimpleAdLoaded에서 setNativeSimpleAd 이후 load처리(visible) 하지 않는 경우 onImpress 및 onError 모두 발생하지 않고 있으며, setNativeSimpleAd 에서 load 처리 하는 경우에는 error 가 발생하고 있습니다.
라이브러리 내부에서 발생하고 있는 에러 이슈에 대한 검토가 필요한 상태 인걸로 보이는데요.

**Comment by zaphike** [comment]
> 혹시 괜찮으시다면 유선상으로 이야기 가능하실까요?

02-6119-3648 입니다.

**Comment by kidoohan** [comment]
@zaphike 님 혹시 `GfpNativeSimpleAdView#setNativeSimpleAdView()` method 가 연달아 두번 호출되는 케이스가 있으실까요?

**Comment by zaphike** [comment]
> @zaphike 님 혹시 `GfpNativeSimpleAdView#setNativeSimpleAdView()` method 가 연달아 두번 호출되는 케이스가 있으실까요?

로그 상으로 그런 상태는 아닌 것으로 보이며, setNativeSimpleAdView 는 onNativeSimpleAdLoaded 와 pair 로 적용되어 있습니다.

**Comment by kidoohan** [comment]
> > @zaphike 님 혹시 `GfpNativeSimpleAdView#setNativeSimpleAdView()` method 가 연달아 두번 호출되는 케이스가 있으실까요?
> 
> 로그 상으로 그런 상태는 아닌 것으로 보이며, setNativeSimpleAdView 는 onNativeSimpleAdLoaded 와 pair 로 적용되어 있습니다.
> 
> 1. 갱신 기능은 있습니다.
> 2. 최초 로드 시에도 동일한 에러가 발생합니다.

최초 로드라면 갱신이 아닌 첫 화면에서 광고가 로드되자마자 공유주신 오류가 발생한다는 것으로 이해하면 될까요?

만약 아니라면, `setNativeSimpleAdView` 를 호출하기에 앞서서 https://github.com/naver/nam-sdk-android/blob/main/doc/native_simple.md#step-6-%EA%B4%91%EA%B3%A0-%EC%82%AD%EC%A0%9C 에 나와있는 광고 삭제를 수행 후 `setNativeSimpleAdView` 를 호출해주실 수 있을까요?

**Comment by zaphike** [comment]
> > > @zaphike 님 혹시 `GfpNativeSimpleAdView#setNativeSimpleAdView()` method 가 연달아 두번 호출되는 케이스가 있으실까요?
> > 
> > 
> > 로그 상으로 그런 상태는 아닌 것으로 보이며, setNativeSimpleAdView 는 onNativeSimpleAdLoaded 와 pair 로 적용되어 있습니다.
> > 
> > 1. 갱신 기능은 있습니다.
> > 2. 최초 로드 시에도 동일한 에러가 발생합니다.
> 
> 최초 로드라면 갱신이 아닌 첫 화면에서 광고가 로드되자마자 공유주신 오류가 발생한다는 것으로 이해하면 될까요?
> 
> 만약 아니라면, `setNativeSimpleAdView` 를 호출하기에 앞서서 https://github.com/naver/nam-sdk-android/blob/main/doc/native_simple.md#step-6-%EA%B4%91%EA%B3%A0-%EC%82%AD%EC%A0%9C 에 나와있는 광고 삭제를 수행 후 `setNativeSimpleAdView` 를 호출해주실 수 있을까요?

네, 발생합니다.
adLoader.cancel() 을 말씀 하신 거라면, loadAd 전에 호출 하고 있습니다.

**Comment by kwonjae-lee** [comment]
@zaphike 님 안녕하세요
이전에 공유주신 코드를 보니 저희 api를 랩핑하여 사용하시는 것 같습니다.
https://github.com/naver/nam-sdk-android/issues/3#issuecomment-1153484847
그래서 어떻게 사용하고 계신지 잘 파악이 안되는데요.
아래의 샘플 코드를 반영해 두었습니다.
https://github.com/naver/nam-sdk-android/blob/main/example/kotlin/namexample/app/src/main/java/com/naver/namexample/sample/SmartchannelFragment.kt

샘플 참고하시어 확인 부탁드립니다.

**Comment by zaphike** [comment]
이전 가이드와 새로 반영해 주신 샘플 코드에서 특별히 달라진 점이 있는지 모르겠습니다.
gone 상태의 GfpNativeSimpleAdView 를 아래와 같이 사용 중이며,
onNativeSimpleAdLoaded 발생시 visible 전환되도록 적용하였습니다.

    fun loadAd(useCache: Boolean) {
        if (DEBUG) {
            Qlog.d(TAG, "loadAd ad_id = $adUnitId, useCache : $useCache")
        }

        adLoader?: initNewAdView()

        adLoader?.cancel()
        adLoader?.loadAd()
    }

    private fun initNewAdView() {
        val adid = adUnitId?: return
        //광고 요청 파라미터
        val adParam: AdParam = AdParam.Builder()
                .setAdUnitId(adid)
                .build()

        val adOptions = GfpNativeSimpleAdOptions.Builder()
                .setAdChoicePlacement(GfpNativeSimpleAdOptions.ADCHOICES_TOP_RIGHT)
                .build()

        val loader = adLoader?: Builder(context, adParam)
                .withTimeoutMillis(MAX_DELAY_LOAD)
                .withNativeSimpleAd(adOptions) { nativeSimpleAd -> // 배너 광고 load 가 성공했을 때 실행됩니다.
                    if (DEBUG) {
                        Qlog.d(TAG, "onNativeSimpleAdLoaded ad info[${nativeSimpleAd?.responseInfo}]")
                    }

                    nativeSimpleAd?.let {
                        setNativeSimpleAd(it)
                    }
                    adsEventListener?.onLoad(AD_TYPE_NAVER_NS, adUnitId, LOAD_CODE_SUCCESS)
                }
                .withAdListener(object : AdEventListener() {

                    override fun onAdClicked() {
                        // 광고를 클릭했을 경우
                        if(DEBUG) {
                            Qlog.e(TAG, "onAdClicked")
                        }

                        adsEventListener?.onClick(AD_TYPE_NAVER_NS, adUnitId, null)
                    }

                    override fun onAdImpression() {
                        // 광고의 노출이 발생했을 경우
                        if(DEBUG) {
                            Qlog.e(TAG, "onAdImpression")
                        }
                    }

                    override fun onAdSizeChanged(p0: GfpBannerAdSize?) {
                        if (DEBUG) {
                            Qlog.e(TAG, "onAdSizeChanged $p0")
                        }
                    }

                    override fun onError(error: GfpError?, p1: GfpResponseInfo?) {
                        // 광고 로드 또는 렌더링 시에 오류가 발생했을 경우
                        if (DEBUG) {
                            Qlog.e(TAG, "onError $error")
                        }
                        adsEventListener?.onLoad(AD_TYPE_NAVER_NS, adUnitId, NOT_DEFINED_ERROR)
                    }
                })
                .build()

        adLoader = loader
    }

**Comment by kwonjae-lee** [comment]
@zaphike 님 최근 변경된 내용은 없습니다.
그리고 샘플 프로젝트에 사용하시는 테스트 유닛과 publisher code를 적용해서 테스트 했을때 이상이 없습니다.
1달 전쯤 난독화 문제로 리스너 클래스(OnNativieSimpleAdLoadedListener) 이름이 보이지 않는 문제가 있어서 새로 업데이트 했던 부분이 있는데요.
https://github.com/naver/nam-sdk-android/tree/main/release
해당 부분이 반영 됐는지 확인 한번 부탁드립니다.

**Comment by kwonjae-lee** [comment]
@zaphike 님 안녕하세요~ 혹시 문제는 해결 됐을까요?

**Comment by zaphike** [comment]
> @zaphike 님 안녕하세요~ 혹시 문제는 해결 됐을까요?

네, remove 하지 않는 것으로 보완하였습니다.

**Comment by kwonjae-lee** [comment]
해결되어 다행이네요
이 이슈는 닫도록 하겠습니다~
