### ISSUE TITLE
5.3.0 -> 6.0.1 버전 업데이트 후 GfpBannerAdView 동작 문의

### ISSUE THREAD

**Issue by zaphike** [naver/nam-sdk-android#31]
### Problem Statement

SDK 버전 : com.naver.gfpsdk:nam-core:6.0.1

안녕하세요.
최신 버전 적용을 위해 검토 중 아래와 같은 현상이 발생하여 확인차 문의 드립니다.

현상 : GfpBannerAdView add 시 아래와 같이 정사각형 형태로 노출 됩니다. (밀리타~ 커피머신 광고 입니다.)
GfpBannerAdView 옵션으로 FLUID_WIDTH 사용 중입니다.
해당 화면을 layout inspector 로 확인 시 GfpBannerAdView child 로 d0의 크기가 작게 잡히고 있습니다.

<img width="677" alt="스크린샷 2023-05-30 오후 7 11 41" src="https://github.com/naver/nam-sdk-android/assets/107376800/cdc87907-6eb7-412a-9272-31ed84a24bc1">

<img width="379" alt="스크린샷 2023-05-30 오후 7 12 06" src="https://github.com/naver/nam-sdk-android/assets/107376800/a2d12fc2-6b62-4135-87b4-bd615a9e6b0a">

혹시 관련 수정 사항이 있는지, 추가 가이드가 있는지 문의 드립니다.
감사합니다.

**Comment by kidoohan** [comment]
@zaphike 님 안녕하세요. 확인해보니 6.x 버전에서 변경된 코드에서 FLUID 처리가 정상적으로 동작하지 않는 부분 확인하였고 

해당부분 수정하여 오늘 중으로 수정된 버전 배포하도록 하겠습니다. 

이슈 공유 감사합니다:)

**Comment by kidoohan** [comment]
@zaphike 님 방금 6.0.2 버전이 배포되어서 공유드립니다. 해당 버전부터 FLUID 관련 버그는 수정되었습니다:)

다시 한번 이슈 공유 감사드립니다:)

**Comment by zaphike** [comment]
네, 감사합니다 👍

**Comment by kidoohan** [comment]
확인 후 이슈 없으시다는 사인 주시면 이슈 클로즈 하도록 하겠습니다:)

**Comment by zaphike** [comment]
네, 이슈 없는 것으로 확인 하였습니다~

**Comment by kidoohan** [comment]
@zaphike 님 번거로우시겠지만 올려주신 https://github.com/naver/nam-sdk-android/issues/28 이슈도 닫아도 되는지 확인 부탁드립니다:)

**Comment by zaphike** [comment]
넵, package name 특이사항 없는 것으로 확인 하였습니다~
