### ISSUE TITLE
해상도 대응 문의

### ISSUE THREAD

**Issue by zaphike** [naver/nam-sdk-android#5]
### Problem Statement

<img width="1449" alt="스크린샷 2022-06-24 오후 4 11 57" src="https://user-images.githubusercontent.com/107376800/175483329-d970dd6c-8db3-430d-b9b8-3b2f90a25d11.png">

**Comment by kwonjae-lee** [comment]
@zaphike 안녕하세요
1. 하단 여백 발생
캡쳐주신 화면 보니 모두 하단에 분홍색 영역이 보이는데요.
해당 부분 문의 주신게 맞을까요?
SDK에서 광고 영역에 margin이나 padding을 주는 것은 없습니다.
광고의 view (GfpNativeSimpleAdView 나 GfpBannerAdView)나
해당 광고의 상위 view container에 여백을 넣으신 부분이 있는지 확인 부탁드립니다.
그리고 높이 값에 대해서 'wrap_content' 로 설정 되었는지도 같이 확인 부탁드립니다.

2. 배너 광고 좌우 여백 문의
배너 광고의 경우 네이버의 mraid 스펙을 따르는 일부 소재가 아니면 고정된 크기로 렌더링 됩니다.
지원하는 배너 광고 크기는 확인 후 추가 답변 드리겠습니다.
그리고 NS형 광고의 경우 높이나 너비에 맞춰서 렌더링 됩니다.
높이/너비 비율에 맞추어 view가 커진다면 좌우 공백 없이 렌더링 될 것 같습니다.

**Comment by zaphike** [comment]
> @zaphike 안녕하세요
> 
> 1. 하단 여백 발생
>    캡쳐주신 화면 보니 모두 하단에 분홍색 영역이 보이는데요.
>    해당 부분 문의 주신게 맞을까요?
>    SDK에서 광고 영역에 margin이나 padding을 주는 것은 없습니다.
>    광고의 view (GfpNativeSimpleAdView 나 GfpBannerAdView)나
>    해당 광고의 상위 view container에 여백을 넣으신 부분이 있는지 확인 부탁드립니다.
>    그리고 높이 값에 대해서 'wrap_content' 로 설정 되었는지도 같이 확인 부탁드립니다.
> 2. 배너 광고 좌우 여백 문의
>    배너 광고의 경우 네이버의 mraid 스펙을 따르는 일부 소재가 아니면 고정된 크기로 렌더링 됩니다.
>    지원하는 배너 광고 크기는 ~확인 후 추가 답변 드리겠습니다.~ 360 * 185 1개 사이즈만 지원하고 있다고 합니다.
>    그리고 NS형 광고의 경우 높이나 너비에 맞춰서 렌더링 됩니다.
>    높이/너비 비율에 맞추어 view가 커진다면 좌우 공백 없이 렌더링 될 것 같습니다.

1. 분홍색 부분은 적용한 마진 영역이고, 그 위의 붉은 선 이 AdView 하단 으로 보입니다.
2. BannerViewLayoutType 을 통해 비율이 맞지 않아도 지원되는 것이 아닌가요?

**Comment by kwonjae-lee** [comment]
@zaphike 
1. 분홍색 부분은 적용한 마진 영역이고, 그 위의 붉은 선 이 AdView 하단 으로 보입니다.
    - NativeSimple (캡쳐 왼쪽 첫번째)
'1st 화면' 이라고 적어주신 부분에 대한 문의인가요?
앞서 말씀드린대로 높이나 너비에 맞춰 렌더링 됩니다.
비율에 맞춰 너비를 채우다 보니 높이가 설정하신 view보다 작아보이는 것 같습니다.
서비스 핏에 맞추어서 높이를 `wrap_content` 로 설정하시거나 비율대로 크기가 조정되어야 할 것 같습니다.
    - 배너 (캡쳐 가운데)
서비스 핏에 맞추어서 `wrap_content` 로 설정하시거나 지원하는 크기대로 설정되어야 할 것 같습니다.
2. BannerViewLayoutType 을 통해 비율이 맞지 않아도 지원되는 것이 아닌가요?
네, 모든 소재에 지원되는 것은 아닙니다.
고정된 크기로 내려온다고 이해해 주시는 것이 좋겠습니다.

**Comment by kwonjae-lee** [comment]
@zaphike 안녕하세요~
형석님 답변 이후 해결이 된 상태일까요?

- 형석님 메일 내용
> 모바일 배너는 기기 너비 385 이상부터는 여백이 발생할 수 있는 구조라 아래와 같이 설정하는 것을 권장하고 있습니다 :  
(아래 이메일의 "고정 높이값" 적용에 대한 부분은 무시 부탁드립니다)
기준 높이값을 185로 설정
높이 가변(wrap_content)이 가능하다면 기기 너비 385 미만에서 스케일 조절하는 형태로 적용
>
> 혹시 위와 같이 설정된 상태인데도 여백 이슈가 재현되는 상황일까요? 
Native Simple 또한 고정 높이값이 적용되지 않은 상태에서도 여백 이슈가 재현되는지 다시 확인해 주시면 감사하겠습니다.

**Comment by kwonjae-lee** [comment]
혹시 같은 내용의 문의 사항이 있으시면 다시 열어주시고, 추가 문의 사항이 있으시면 새로 등록 부탁드립니다~ (__)
