### ISSUE TITLE
화면 크게/작게에 따른 현상을 캡쳐

### ISSUE THREAD

**Issue by zaphike** [naver/nam-sdk-android#6]
### Problem Statement

화면 크게/작게에 따른 현상을 캡쳐해서 파일로 만들었습니다
갤럭시 S10+
Android 12,
One UI 4.1

![그림2](https://user-images.githubusercontent.com/107376800/175919930-406c912a-b0fe-4cf2-91e3-b17b60a415e9.png)

**Comment by kwonjae-lee** [comment]
#5 와 같은 내용으로 생각되어 닫습니다.
혹시 대응이 필요하시다면 다시 열어주세요~ (__)
